# Generated by Django 2.1.13 on 2019-10-06 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharing_credit', models.IntegerField()),
                ('using_credit', models.IntegerField()),
                ('rate', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('root_path', models.CharField(blank=True, default='', max_length=128)),
                ('core_num', models.IntegerField()),
                ('machine_type', models.CharField(blank=True, default='GPU', max_length=40)),
                ('status', models.CharField(blank=True, default='Available', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_type', models.CharField(blank=True, default='GPU', max_length=40)),
                ('ip_address', models.CharField(blank=True, default='127.0.0.1', max_length=64)),
                ('service_port', models.CharField(blank=True, default='8000', max_length=32)),
                ('core_num', models.IntegerField(blank=True, default=1)),
                ('memory_size', models.FloatField(null=True)),
                ('time_period', models.IntegerField(null=True)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='', max_length=200)),
                ('credit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.Credit')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
